import "./D1_Variables_and_Datatypes/index.js";
import "./D2_Operators/index.js";
import "./D2_Operators/artihmetic.js";
import "./D2_Operators/logical.js";
import "./D2_Operators/ternary.js";
import "./D3_Control Structures/index.js";
import "./D4_Loops/index.js";
import "./D5_Functions/index.js";
import "./D6_Arrays/index.js";
import "./D7_Objects/index.js";
import "./D8_ES6+ Features/index.js";
import "./D9_DOM Manipulation/index.js";
import "./D10_Event Handling/index.js";
import "./D11_Promises and Async Await/index.js";
import "./D12_Error Handling/index.js";
import "./D13_Modules/index.js";
import "./D14_Classes/index.js";
import "./D15_Closures/index.js";
